[package]
name = "binary-wallpapers"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
image = "0.25.5"
imageproc = "0.25.0"
flate2 = "1.0.35"
clap = { version = "4.5.28", features = ["derive"] }
